import pandas as pd

def load_and_clean_water_data(file_path):
    df = pd.read_excel(file_path)

    # Always show the raw column names for debugging
    print("🧾 Raw columns from Excel:", df.columns.tolist())

    # Normalize 'name' column to remove extra whitespace
    if 'name' in df.columns:
        df['name'] = df['name'].astype(str).str.strip()

    target_sites = [
    "Abingdon STW - River Downstream",
    "Abingdon STW - River Upstream",
    "Abingdon STW - Treatment Effluent",
    "Acle STW - River Downstream",
    "Acle STW - Treatment Effluent",
    "Adwick le Street STW - River Downstream",
    "Adwick le Street STW - River Upstream",
    "Adwick le Street STW - Treatment Effluent",
    "Adwick le Street STW - Treatment Influent",
    "Ainsdale STW - River Downstream",
    "Ainsdale STW - River Upstream",
    "Ainsdale STW - Treatment Effluent",
    "Alconbury STW - River Downstream",
    "Alconbury STW - Treatment Effluent",
    "Alderley Edge STW - River Downstream",
    "Alderley Edge STW - River Upstream",
    "Alderley Edge STW - Treatment Effluent",
    "Aldermaston STW - River Downstream",
    "Aldermaston STW - River Upstream",
    "Aldermaston STW - Treatment Effluent",
    "Aldershot STW - River Downstream",
    "Aldershot STW - River Upstream",
    "Aldershot STW - Treatment Effluent",
    "Aldwarke STW - River Downstream",
    "Aldwarke STW - River Upstream",
    "Aldwarke STW - Treatment Effluent",
    "Alford STW - River Downstream",
    "Alford STW - River Upstream",
    "Alford STW - Treatment Effluent",
    "Alfreton STW - River Downstream",
    "Alfreton STW - River Upstream",
    "Alfreton STW - Treatment Effluent",
    "Alsager STW - River Downstream",
    "Alsager STW - River Upstream",
    "Alsager STW - Treatment Effluent",
    "Alstonfield STW - Down Gradient",
    "Alstonfield STW - Treatment Effluent",
    "Alton STW - River Downstream",
    "Alton STW - River Upstream",
    "Alton STW - Treatment Effluent",
    "Altrincham STW - River Downstream",
    "Altrincham STW - River Upstream",
    "Altrincham STW - Treatment Effluent",
    "Alvechurch STW - River Downstream",
    "Alvechurch STW - River Upstream",
    "Alvechurch STW - Treatment Effluent",
    "Alwinton STW - Down Gradient",
    "Ambergate STW - River Downstream",
    "Ambergate STW - River Upstream",
    "Ambergate STW - Treatment Effluent",
    "Ambleside STW - River Upstream",
    "Ambleside STW - Treatment Effluent",
    "Ancaster STW - River Downstream",
    "Ancaster STW - River Upstream",
    "Ancaster STW - Treatment Effluent",
    "Appleton STW - River Downstream",
    "Appleton STW - River Upstream",
    "Appleton STW - Treatment Effluent",
    "Arborfield STW - River Downstream",
    "Arborfield STW - River Upstream",
    "Arborfield STW - Treatment Effluent",
    "Armthorpe STW - River Downstream",
    "Armthorpe STW - River Upstream",
    "Armthorpe STW - Treatment Effluent",
    "Ascot STW - River Downstream",
    "Ascot STW - Treatment Effluent",
    "Ash Vale STW - River Downstream",
    "Ash Vale STW - River Upstream",
    "Ash Vale STW - Treatment Effluent",
    "Ashford STW - River Downstream",
    "Ashford STW - River Upstream",
    "Ashford STW - Treatment Effluent",
    "Ashton STW - River Downstream",
    "Ashton STW - River Upstream",
    "Ashton STW - Treatment Effluent",
    "Aspatria STW - River Downstream",
    "Aspatria STW - River Upstream",
    "Aspatria STW - Treatment Effluent",
    "Astwood Bank STW - River Downstream",
    "Astwood Bank STW - River Upstream",
    "Astwood Bank STW - Treatment Effluent",
    "Attleborough STW - River Downstream",
    "Attleborough STW - River Upstream",
    "Attleborough STW - Treatment Effluent",
    "Avonmouth STW - Treatment Effluent",
    "Avonmouth STW - Treatment Influent",
    "Aycliffe STW - River Downstream",
    "Aycliffe STW - River Upstream",
    "Aycliffe STW - Treatment Effluent",
    "Aylesbury STW - River Downstream",
    "Aylesbury STW - River Upstream",
    "Aylesbury STW - Treatment Effluent",
    "Aylesford STW - River Downstream",
    "Aylesford STW - River Upstream",
    "Aylesford STW - Spread To land",
    "Aylesford STW - Treatment Effluent",
    "Aylsham STW - River Downstream",
    "Aylsham STW - River Upstream",
    "Aylsham STW - Treatment Effluent",
    "Balby STW - River Downstream",
    "Balby STW - River Upstream",
    "Balby STW - Treatment Effluent",
    "Balsall Common STW - River Downstream",
    "Balsall Common STW - River Upstream",
    "Balsall Common STW - Treatment Effluent",
    "Barlestone STW - River Downstream",
    "Barlestone STW - River Upstream",
    "Barlestone STW - Treatment Effluent",
    "Barnhurst STW - River Downstream",
    "Barnhurst STW - River Upstream",
    "Barnhurst STW - Treatment Effluent",
    "Barnoldswick STW - River Downstream",
    "Barnoldswick STW - River Upstream",
    "Barnoldswick STW - Treatment Effluent",
    "Barrow STW - River Downstream",
    "Barrow STW - River Upstream",
    "Barrow STW - Treatment Effluent",
    "Barston STW - On STW Site",
    "Barton Le Clay STW - River Downstream",
    "Barton Le Clay STW - River Upstream",
    "Barton Le Clay STW - Treatment Effluent",
    "Barton STW - River Downstream",
    "Barton STW - River Upstream",
    "Barton STW - Treatment Effluent",
    "Barwick STW - River Downstream",
    "Barwick STW - River Upstream",
    "Barwick STW - Treatment Effluent",
    "Basingstoke STW - River Downstream",
    "Basingstoke STW - River Upstream",
    "Basingstoke STW - Treatment Effluent",
    "Bassingbourn STW - River Downstream",
    "Bassingbourn STW - River Upstream",
    "Bassingbourn STW - Treatment Effluent",
    "Battle STW - On STW Site",
    "Battle STW - River Downstream",
    "Battle STW - River Upstream",
    "Battle STW - Treatment Effluent",
    "Beckton STW - Treatment Effluent",
    "Beckton STW - Treatment Influent",
    "Beddington STW - River Downstream",
    "Beddington STW - River Upstream",
    "Beddington STW - Treatment Effluent",
    "Bedworth STW - River Downstream",
    "Bedworth STW - River Upstream",
    "Bedworth STW - Treatment Effluent",
    "Benhall STW - River Downstream",
    "Benhall STW - River Upstream",
    "Benhall STW - Treatment Effluent",
    "Benson STW - River Downstream",
    "Benson STW - River Upstream",
    "Benson STW - Treatment Effluent",
    "Bentley STW - River Downstream",
    "Bentley STW - River Upstream",
    "Bentley STW - Treatment Effluent",
    "Berkhamsted STW - River Downstream",
    "Berkhamsted STW - River Upstream",
    "Berkhamsted STW - Treatment Effluent",
    "Bethersden STW - River Downstream",
    "Bethersden STW - River Upstream",
    "Bethersden STW - Treatment Effluent",
    "Beverley STW - River Downstream",
    "Beverley STW - River Upstream",
    "Beverley STW - Treatment Effluent",
    "Bicester STW - River Downstream",
    "Bicester STW - River Upstream",
    "Bicester STW - Treatment Effluent",
    "Bidborough STW - River Downstream",
    "Bidborough STW - River Upstream",
    "Bidborough STW - Treatment Effluent",
    "Biddenden STW - River Downstream",
    "Biddenden STW - River Upstream",
    "Biddenden STW - Treatment Effluent",
    "Biddulph STW - River Downstream",
    "Biddulph STW - River Upstream",
    "Biddulph STW - Treatment Effluent",
    "Billinghurst STW - River Downstream",
    "Billinghurst STW - River Upstream",
    "Billinghurst STW - Sewer Catchment",
    "Billinghurst STW - Treatment Effluent",
    "Billinghurst STW - Treatment Influent",
    "Bilsthorpe STW - River Downstream",
    "Bilsthorpe STW - River Upstream",
    "Bilsthorpe STW - Treatment Effluent",
    "Birdlip STW - Down Gradient",
    "Birdlip STW - Treatment Effluent",
    "Birkenhead STW - Treatment Effluent",
    "Birtley STW - River Downstream",
    "Birtley STW - River Upstream",
    "Birtley STW - Treatment Effluent",
    "Bishops Stortford STW - River Downstream",
    "Bishops Stortford STW - River Upstream",
    "Bishops Stortford STW - Treatment Effluent",
    "Blackbirds STW - River Downstream",
    "Blackbirds STW - River Upstream",
    "Blackbirds STW - Treatment Effluent",
    "Blackburn Meadows STW - River Downstream",
    "Blackburn Meadows STW - River Upstream",
    "Blackburn Meadows STW - Treatment Effluent",
    "Blackminster STW - River Downstream",
    "Blackminster STW - Treatment Effluent",
    "Blagdon STW - River Downstream",
    "Blagdon STW - River Upstream",
    "Blagdon STW - Treatment Effluent",
    "Blyton STW - River Downstream",
    "Blyton STW - River Upstream",
    "Blyton STW - Treatment Effluent",
    "Bocking STW - River Downstream",
    "Bocking STW - River Upstream",
    "Bocking STW - Treatment Effluent",
    "Bodmin STW - River Downstream",
    "Bodmin STW - River Upstream",
    "Bodmin STW - Treatment Effluent",
    "Bolton STW - River Downstream",
    "Bolton STW - River Upstream",
    "Bolton STW - Treatment Effluent",
    "Bomere Heath STW - River Downstream",
    "Bomere Heath STW - Treatment Effluent",
    "Bordon STW - River Downstream",
    "Bordon STW - River Upstream",
    "Bordon STW - Treatment Effluent",
    "Bottesford STW - River Downstream",
    "Bottesford STW - River Upstream",
    "Bottesford STW - Treatment Effluent",
    "Bottisham STW - River Downstream",
    "Bottisham STW - Treatment Effluent",
    "Bourn STW - River Downstream",
    "Bourn STW - Treatment Effluent",
    "Bourne STW - River Downstream",
    "Bourne STW - River Upstream",
    "Bourne STW - Treatment Effluent",
    "Bourton STW - River Downstream",
    "Bourton STW - Treatment Effluent",
    "Bowburn STW - On STW Site",
    "Bowburn STW - River Downstream",
    "Bowburn STW - River Upstream",
    "Bowburn STW - Treatment Effluent",
    "Bowerhill STW - River Downstream",
    "Bowerhill STW - River Upstream",
    "Bowerhill STW - Treatment Effluent",
    "Bowerhill STW - Treatment Influent",
    "Brackley New STW - River Downstream",
    "Brackley New STW - River Upstream",
    "Brackley New STW - Treatment Effluent",
    "Bracknell STW - River Downstream",
    "Bracknell STW - River Upstream",
    "Bracknell STW - Treatment Effluent",
    "Braintree STW - River Downstream",
    "Braintree STW - River Upstream",
    "Braintree STW - Treatment Effluent",
    "Braithwell STW - River Downstream",
    "Braithwell STW - Treatment Effluent",
    "Bran Sands STW - Treatment Effluent",
    "Branton STW - River Downstream",
    "Branton STW - River Upstream",
    "Branton STW - Treatment Effluent",
    "Brentwood STW - River Downstream",
    "Brentwood STW - River Upstream",
    "Brentwood STW - Treatment Effluent",
    "Bridlington STW - Treatment Effluent",
    "Bridlington STW - Treatment Influent",
    "Brigg STW - River Downstream",
    "Brigg STW - River Upstream",
    "Brigg STW - Treatment Effluent",
    "Brinkworth Brook STW - River Downstream",
    "Brinkworth Brook STW - River Upstream",
    "Brixworth STW - River Downstream",
    "Brixworth STW - River Upstream",
    "Brixworth STW - Treatment Effluent",
    "Broadholme STW - River Downstream",
    "Broadholme STW - River Upstream",
    "Broadholme STW - Treatment Effluent",
    "Broadway STW - River Downstream",
    "Broadway STW - Treatment Effluent",
    "Bromborough STW - Treatment Effluent",
    "Bromsgrove STW - River Downstream",
    "Bromsgrove STW - River Upstream",
    "Bromsgrove STW - Treatment Effluent",
    "Broughton STW - River Downstream",
    "Broughton STW - Treatment Effluent",
    "Buckland STW - Spread To land",
    "Buckley Ty Gwyn WWTW - Treatment Effluent",
    "Buckley Ty Gwyn WWTW - Treatment Influent",
    "Bulkington STW - River Downstream",
    "Bulkington STW - River Upstream",
    "Bulkington STW - Treatment Effluent",
    "Bungay STW - River Downstream",
    "Bungay STW - River Upstream",
    "Bungay STW - Treatment Effluent",
    "Buntingford STW - River Downstream",
    "Buntingford STW - River Upstream",
    "Buntingford STW - Treatment Effluent",
    "Burghfield STW - River Downstream",
    "Burghfield STW - River Upstream",
    "Burghfield STW - Treatment Effluent",
    "Burnley STW - River Downstream",
    "Burnley STW - River Upstream",
    "Burnley STW - Treatment Effluent",
    "Burntwood STW - River Downstream",
    "Burntwood STW - River Upstream",
    "Burntwood STW - Treatment Effluent",
    "Burscough STW - River Downstream",
    "Burscough STW - River Upstream",
    "Burscough STW - Treatment Effluent",
    "Burstow STW - River Downstream",
    "Burstow STW - River Upstream",
    "Burstow STW - Treatment Effluent",
    "Burton Fleming STW - Down Gradient",
    "Burton on the Wolds STW - River Downstream",
    "Burton on the Wolds STW - Treatment Effluent",
    "Burwell STW - River Downstream",
    "Burwell STW - River Upstream",
    "Burwell STW - Treatment Effluent",
    "Bury STW - River Downstream",
    "Bury STW - River Upstream",
    "Bury STW - Treatment Effluent",
    "Byfield STW - River Downstream",
    "Byfield STW - River Upstream",
    "Byfield STW - Treatment Effluent",
    "Callington STW - River Downstream",
    "Callington STW - River Upstream",
    "Callington STW - Treatment Effluent",
    "Calverton STW - River Downstream",
    "Calverton STW - River Upstream",
    "Calverton STW - Treatment Effluent",
    "Camberley STW - On STW Site",
    "Camberley STW - River Downstream",
    "Camberley STW - River Upstream",
    "Camberley STW - Treatment Effluent",
    "Cambridge STW - River Downstream",
    "Cambridge STW - River Upstream",
    "Cambridge STW - Treatment Effluent",
    "Cannock STW - River Downstream",
    "Cannock STW - River Upstream",
    "Cannock STW - Treatment Effluent",
    "Canwick STW - River Downstream",
    "Canwick STW - River Upstream",
    "Canwick STW - Treatment Effluent",
    "Cardiff STW - Treatment Effluent",
    "Cardiff STW - Treatment Influent",
    "Carleton STW - River Downstream",
    "Carleton STW - River Upstream",
    "Carleton STW - Treatment Effluent",
    "Carlisle STW - River Upstream",
    "Carlisle STW - Treatment Effluent",
    "Castle Cary STW - River Downstream",
    "Castle Cary STW - River Upstream",
    "Castle Cary STW - Treatment Effluent",
    "Castle Donington STW - River Downstream",
    "Castle Donington STW - River Upstream",
    "Castle Donington STW - Treatment Effluent",
    "Cawthorne STW - River Downstream",
    "Cawthorne STW - River Upstream",
    "Cawthorne STW - Treatment Effluent",
    "Caythorpe STW - River Downstream",
    "Caythorpe STW - Treatment Effluent",
    "Chadlington STW - River Downstream",
    "Chadlington STW - River Upstream",
    "Chadlington STW - Treatment Effluent",
    "Chalgrove STW - River Downstream",
    "Chalgrove STW - Treatment Effluent",
    "Chalton STW - River Downstream",
    "Chalton STW - River Upstream",
    "Chalton STW - Treatment Effluent",
    "Chantry STW - River Downstream",
    "Chantry STW - River Upstream",
    "Chantry STW - Treatment Effluent",
    "Chapel-en-le- Frith STW - River Downstream",
    "Chapel-en-le- Frith STW - River Upstream",
    "Chapel-en-le- Frith STW - Treatment Effluent",
    "Chedburgh STW - River Downstream",
    "Chedburgh STW - River Upstream",
    "Chedburgh STW - Treatment Effluent",
    "Chelmorton - Down Gradient",
    "Chelmorton - Treatment Effluent",
    "Cherry Burton STW - River Downstream",
    "Cherry Burton STW - River Upstream",
    "Cherry Burton STW - Treatment Effluent",
    "Cherry Burton STW - Treatment Influent",
    "Chertsey STW - River Downstream",
    "Chertsey STW - River Upstream",
    "Chertsey STW - Treatment Effluent",
    "Chesham STW - River Downstream",
    "Chesham STW - River Upstream",
    "Chesham STW - Treatment Effluent",
    "Chester Le Street STW - River Downstream",
    "Chester Le Street STW - River Upstream",
    "Chester Le Street STW - Treatment Effluent",
    "Chew Stoke STW - River Downstream",
    "Chew Stoke STW - River Upstream",
    "Chew Stoke STW - Treatment Effluent",
    "Chichester - Treatment Effluent",
    "Chichester - Treatment Influent",
    "Chieveley STW - On STW Site",
    "Chieveley STW - River Downstream",
    "Chieveley STW - River Upstream",
    "Chieveley STW - Treatment Effluent",
    "Chilton STW - River Downstream",
    "Chilton STW - Treatment Effluent",
    "Chilton and Windlestone STW - River Downstream",
    "Chilton and Windlestone STW - River Upstream",
    "Chilton and Windlestone STW - Sewer Catchment",
    "Chilton and Windlestone STW - Treatment Effluent",
    "Chilton and Windlestone STW - Treatment Influent",
    "Chinnor STW - River Downstream",
    "Chinnor STW - River Upstream",
    "Chinnor STW - Treatment Effluent",
    "Chobham STW - River Downstream",
    "Chobham STW - River Upstream",
    "Chobham STW - Treatment Effluent",
    "Cholsey STW - River Downstream",
    "Cholsey STW - River Upstream",
    "Cholsey STW - Treatment Effluent",
    "Chorley STW - River Downstream",
    "Chorley STW - River Upstream",
    "Chorley STW - Treatment Effluent",
    "Church Hanborough STW - River Downstream",
    "Church Hanborough STW - River Upstream",
    "Church Hanborough STW - Treatment Effluent",
    "Church Stretton STW - River Downstream",
    "Church Stretton STW - River Upstream",
    "Church Stretton STW - Treatment Effluent",
    "Cirencester STW - River Downstream",
    "Cirencester STW - River Upstream",
    "Cirencester STW - Treatment Effluent",
    "Clavering STW - River Downstream",
    "Clavering STW - River Upstream",
    "Clavering STW - Treatment Effluent",
    "Clay Cross STW - River Downstream",
    "Clay Cross STW - River Upstream",
    "Clay Cross STW - Treatment Effluent",
    "Claymills STW - River Downstream",
    "Claymills STW - River Upstream",
    "Claymills STW - Treatment Effluent",
    "Clayton West STW - River Downstream",
    "Clayton West STW - River Upstream",
    "Clayton West STW - Treatment Effluent",
    "Cleator STW - River Downstream",
    "Cleator STW - River Upstream",
    "Cleator STW - Treatment Effluent",
    "Clitheroe STW - River Downstream",
    "Clitheroe STW - River Upstream",
    "Clitheroe STW - Treatment Effluent",
    "Clive STW - River Downstream",
    "Clive STW - Treatment Effluent",
    "Clowne STW - River Downstream",
    "Clowne STW - River Upstream",
    "Clowne STW - Treatment Effluent",
    "Coaley STW - River Downstream",
    "Coaley STW - River Upstream",
    "Coaley STW - Treatment Effluent",
    "Cockermouth STW - River Downstream",
    "Cockermouth STW - River Upstream",
    "Cockermouth STW - Treatment Effluent",
    "Coggeshall STW - River Downstream",
    "Coggeshall STW - River Upstream",
    "Coggeshall STW - Treatment Effluent",
    "Colwall STW - River Downstream",
    "Colwall STW - River Upstream",
    "Colwall STW - Treatment Effluent",
    "Coney Weston STW - River Downstream",
    "Coney Weston STW - Treatment Effluent",
    "Congleton STW - River Downstream",
    "Congleton STW - River Upstream",
    "Congleton STW - Treatment Effluent",
    "Consett STW - River Downstream",
    "Consett STW - River Upstream",
    "Consett STW - Treatment Effluent",
    "Consett STW - Treatment Influent",
    "Corby STW - River Downstream",
    "Corby STW - River Upstream",
    "Corby STW - Treatment Effluent",
    "Coton Park STW - River Downstream",
    "Coton Park STW - River Upstream",
    "Coton Park STW - Treatment Effluent",
    "Cottesmore STW - River Downstream",
    "Cottesmore STW - Treatment Effluent",
    "Cotton Valley STW - River Downstream",
    "Cotton Valley STW - River Upstream",
    "Cotton Valley STW - Treatment Effluent",
    "Countess Wear STW - Treatment Effluent",
    "Countess Wear STW - Treatment Influent",
    "Coventry Finham STW - On STW Site",
    "Cranbrook STW - River Downstream",
    "Cranbrook STW - River Upstream",
    "Cranbrook STW - Treatment Effluent",
    "Cranleigh STW - River Downstream",
    "Cranleigh STW - River Upstream",
    "Cranleigh STW - Treatment Effluent",
    "Crawley STW - River Downstream",
    "Crawley STW - River Upstream",
    "Crawley STW - Spread To land",
    "Crawley STW - Treatment Effluent",
    "Creswell STW - River Downstream",
    "Creswell STW - Treatment Effluent",
    "Crewe STW - River Downstream",
    "Crewe STW - River Upstream",
    "Crewe STW - Treatment Effluent",
    "Crewe STW - Treatment Influent",
    "Crewkerne E STW - River Downstream",
    "Crewkerne E STW - River Upstream",
    "Crewkerne E STW - Treatment Effluent",
    "Crookhall STW - River Downstream",
    "Crookhall STW - River Upstream",
    "Crookhall STW - Treatment Effluent",
    "Croscombe STW - River Downstream",
    "Croscombe STW - River Upstream",
    "Croscombe STW - Treatment Effluent",
    "Crossness STW - Treatment Effluent",
    "Crowborough STW - River Downstream",
    "Crowborough STW - River Upstream",
    "Crowborough STW - Treatment Effluent",
    "Crowle STW - River Downstream",
    "Crowle STW - Treatment Effluent",
    "Croxton Kerrial STW - River Downstream",
    "Croxton Kerrial STW - River Upstream",
    "Croxton Kerrial STW - Treatment Effluent",
    "Cudworth STW - River Downstream",
    "Cudworth STW - Treatment Effluent",
    "Culham STW - River Downstream",
    "Culham STW - Treatment Effluent",
    "Darley STW - River Downstream",
    "Darley STW - Treatment Effluent",
    "Davyhulme STW - River Downstream",
    "Davyhulme STW - River Upstream",
    "Davyhulme STW - Treatment Effluent",
    "Deepings STW - River Downstream",
    "Deepings STW - River Upstream",
    "Deepings STW - Treatment Effluent",
    "Derby STW - On STW Site",
    "Derby STW - River Downstream",
    "Derby STW - River Upstream",
    "Derby STW - Treatment Effluent",
    "Derby STW - Treatment Influent",
    "Dereham STW - River Downstream",
    "Dereham STW - River Upstream",
    "Dereham STW - Treatment Effluent",
    "Devizes STW - River Downstream",
    "Devizes STW - River Upstream",
    "Devizes STW - Treatment Effluent",
    "Didcot STW - River Downstream",
    "Didcot STW - River Upstream",
    "Didcot STW - Treatment Effluent",
    "Diss STW - River Downstream",
    "Diss STW - River Upstream",
    "Diss STW - Treatment Effluent",
    "Doddinghurst STW - River Downstream",
    "Doddinghurst STW - River Upstream",
    "Doddinghurst STW - Treatment Effluent",
    "Donisthorpe STW - River Downstream",
    "Donisthorpe STW - River Upstream",
    "Donisthorpe STW - Treatment Effluent",
    "Dorchester STW - River Downstream",
    "Dorchester STW - River Upstream",
    "Dorchester STW - Treatment Effluent",
    "Doveholes STW - Down Gradient",
    "Doveholes STW - Treatment Effluent",
    "Driffield STW - River Downstream",
    "Driffield STW - River Upstream",
    "Driffield STW - Treatment Effluent",
    "Droitwich STW - River Downstream",
    "Droitwich STW - River Upstream",
    "Droitwich STW - Treatment Effluent",
    "Dronfield STW - River Downstream",
    "Dronfield STW - River Upstream",
    "Dronfield STW - Treatment Effluent",
    "Dukinfield STW - River Downstream",
    "Dukinfield STW - River Upstream",
    "Dukinfield STW - Treatment Effluent",
    "Dullingham STW - River Downstream",
    "Dullingham STW - River Upstream",
    "Dullingham STW - Treatment Effluent",
    "Dundry STW - Down Gradient",
    "Dundry STW - Treatment Effluent",
    "Dundry STW - Up Gradient",
    "Dunholme STW - River Downstream",
    "Dunholme STW - River Upstream",
    "Dunholme STW - Treatment Effluent",
    "Dunkeswell STW - On STW Site",
    "Dunstable STW - River Downstream",
    "Dunstable STW - River Upstream",
    "Dunstable STW - Treatment Effluent",
    "Duxford STW - River Downstream",
    "Duxford STW - Treatment Effluent",
    "E Grinstead STW - River Downstream",
    "E Grinstead STW - River Upstream",
    "E Grinstead STW - Treatment Effluent",
    "Earlswood STW - River Downstream",
    "Earlswood STW - River Upstream",
    "Earlswood STW - Treatment Effluent",
    "Easingwold STW - River Downstream",
    "Easingwold STW - River Upstream",
    "Easingwold STW - Treatment Effluent",
    "East Bridgford STW - River Downstream",
    "East Bridgford STW - Treatment Effluent",
    "East Harling STW - River Downstream",
    "East Harling STW - River Upstream",
    "East Harling STW - Treatment Effluent",
    "East Markham STW - River Downstream",
    "East Markham STW - Treatment Effluent",
    "East Tanfield STW - On STW Site",
    "East Tanfield STW - River Downstream",
    "East Tanfield STW - River Upstream",
    "East Tanfield STW - Treatment Effluent",
    "East Tanfield STW - Treatment Influent",
    "Easthampstead Pk STW - River Downstream",
    "Easthampstead Pk STW - River Upstream",
    "Easthampstead Pk STW - Treatment Effluent",
    "Eccles STW - River Downstream",
    "Eccles STW - River Upstream",
    "Eccles STW - Treatment Effluent",
    "Eccles STW - Treatment Influent",
    "Eden Vale East Grinstead STW - River Downstream",
    "Eden Vale East Grinstead STW - River Upstream",
    "Eden Vale East Grinstead STW - Treatment Effluent",
    "Edenbridge STW - River Downstream",
    "Edenbridge STW - River Upstream",
    "Edenbridge STW - Treatment Effluent",
    "Edgmond STW - River Downstream",
    "Edgmond STW - River Upstream",
    "Edgmond STW - Treatment Effluent",
    "Edwinstowe STW - River Downstream",
    "Edwinstowe STW - River Upstream",
    "Edwinstowe STW - Treatment Effluent",
    "Eggborough STW - River Downstream",
    "Eggborough STW - River Upstream",
    "Eggborough STW - Treatment Effluent",
    "Ellesmere Port STW - Treatment Effluent",
    "Elmswell STW - River Downstream",
    "Elmswell STW - River Upstream",
    "Elmswell STW - Treatment Effluent",
    "Epping STW - River Downstream",
    "Epping STW - River Upstream",
    "Epping STW - Treatment Effluent",
    "Esh Winning STW - River Downstream",
    "Esh Winning STW - River Upstream",
    "Esh Winning STW - Treatment Effluent",
    "Etwall STW - River Downstream",
    "Etwall STW - River Upstream",
    "Etwall STW - Treatment Effluent",
    "Evercreech STW - River Downstream",
    "Evercreech STW - River Upstream",
    "Evercreech STW - Treatment Effluent",
    "Failsworth STW - On STW Site",
    "Failsworth STW - River Downstream",
    "Failsworth STW - River Upstream",
    "Failsworth STW - Treatment Effluent",
    "Farnham STW - River Downstream",
    "Farnham STW - River Upstream",
    "Farnham STW - Treatment Effluent",
    "Farnsfield STW - River Downstream",
    "Farnsfield STW - Treatment Effluent",
    "Fazakerley STW - River Downstream",
    "Fazakerley STW - River Upstream",
    "Fazakerley STW - Treatment Effluent",
    "Felbridge STW - River Downstream",
    "Felbridge STW - River Upstream",
    "Felbridge STW - Treatment Effluent",
    "Fernhurst STW - River Downstream",
    "Fernhurst STW - River Upstream",
    "Fernhurst STW - Treatment Effluent",
    "Findern STW - River Downstream",
    "Findern STW - River Upstream",
    "Findern STW - Treatment Effluent",
    "Finstock STW - River Downstream",
    "Finstock STW - River Upstream",
    "Finstock STW - Treatment Effluent",
    "Five Fords STW - Spread To land",
    "Fleet STW - River Downstream",
    "Fleet STW - River Upstream",
    "Fleet STW - Treatment Effluent",
    "Flitwick STW - River Downstream",
    "Flitwick STW - River Upstream",
    "Flitwick STW - Treatment Effluent",
    "Foolow STW - Down Gradient",
    "Foolow STW - Treatment Effluent",
    "Formby STW - River Downstream",
    "Formby STW - River Upstream",
    "Formby STW - Treatment Effluent",
    "Fornham STW - River Downstream",
    "Fornham STW - River Upstream",
    "Fornham STW - Treatment Effluent",
    "Foxton Cambs STW - River Downstream",
    "Foxton Cambs STW - River Upstream",
    "Foxton Cambs STW - Treatment Effluent",
    "Fraddon STW - River Downstream",
    "Fraddon STW - River Upstream",
    "Fraddon STW - Treatment Effluent",
    "Framlingham STW - River Downstream",
    "Framlingham STW - River Upstream",
    "Framlingham STW - Treatment Effluent",
    "Fremington STW - Treatment Effluent",
    "Frickley STW - River Downstream",
    "Frickley STW - River Upstream",
    "Frickley STW - Treatment Effluent",
    "Frizington STW - River Downstream",
    "Frizington STW - River Upstream",
    "Frizington STW - Treatment Effluent",
    "Frome STW - River Downstream",
    "Frome STW - River Upstream",
    "Frome STW - Treatment Effluent",
    "Fylingdales STW - River Downstream",
    "Fylingdales STW - River Upstream",
    "Fylingdales STW - Treatment Effluent",
    "Gainsborough STW - River Downstream",
    "Gainsborough STW - River Upstream",
    "Gainsborough STW - Treatment Effluent",
    "Gartree STW - River Downstream",
    "Gartree STW - River Upstream",
    "Gartree STW - Treatment Effluent",
    "Garstang STW - River Downstream",
    "Garstang STW - River Upstream",
    "Garstang STW - Treatment Effluent",
    "Gateshead STW - River Downstream",
    "Gateshead STW - River Upstream",
    "Gateshead STW - Treatment Effluent",
    "Gateshead STW - Treatment Influent",
    "Gerrards Cross STW - River Downstream",
    "Gerrards Cross STW - River Upstream",
    "Gerrards Cross STW - Treatment Effluent",
    "Godalming STW - River Downstream",
    "Godalming STW - River Upstream",
    "Godalming STW - Treatment Effluent",
    "Gomersal STW - River Downstream",
    "Gomersal STW - River Upstream",
    "Gomersal STW - Treatment Effluent",
    "Gorleston STW - Treatment Effluent",
    "Great Oakley STW - River Downstream",
    "Great Oakley STW - Treatment Effluent",
    "Great Staughton STW - River Downstream",
    "Great Staughton STW - Treatment Effluent",
    "Great Wyrley STW - River Downstream",
    "Great Wyrley STW - River Upstream",
    "Great Wyrley STW - Treatment Effluent",
    "Grimsby STW - Treatment Effluent",
    "Hales STW - River Downstream",
    "Hales STW - Treatment Effluent",
    "Halesowen STW - River Downstream",
    "Halesowen STW - River Upstream",
    "Halesowen STW - Treatment Effluent",
    "Hapton Bridge STW - River Downstream",
    "Hapton Bridge STW - River Upstream",
    "Hapton Bridge STW - Treatment Effluent",
    "Harbury STW - River Downstream",
    "Harbury STW - River Upstream",
    "Harbury STW - Treatment Effluent",
    "Hardwick STW - River Downstream",
    "Hardwick STW - River Upstream",
    "Hardwick STW - Treatment Effluent",
    "Harlington STW - River Downstream",
    "Harlington STW - River Upstream",
    "Harlington STW - Treatment Effluent",
    "Harrogate STW - River Downstream",
    "Harrogate STW - River Upstream",
    "Harrogate STW - Treatment Effluent",
    "Harrington STW - River Downstream",
    "Harrington STW - River Upstream",
    "Harrington STW - Treatment Effluent",
    "Harpenden STW - River Downstream",
    "Harpenden STW - River Upstream",
    "Harpenden STW - Treatment Effluent",
    "Hassocks STW - River Downstream",
    "Hassocks STW - River Upstream",
    "Hassocks STW - Treatment Effluent",
    "Hatfield STW - River Downstream",
    "Hatfield STW - River Upstream",
    "Hatfield STW - Treatment Effluent",
    "Haxey STW - River Downstream",
    "Haxey STW - Treatment Effluent",
    "Haydock STW - River Downstream",
    "Haydock STW - River Upstream",
    "Haydock STW - Treatment Effluent",
    "Heathfield STW - River Downstream",
    "Heathfield STW - River Upstream",
    "Heathfield STW - Treatment Effluent",
    "Heckington STW - River Downstream",
    "Heckington STW - River Upstream",
    "Heckington STW - Treatment Effluent",
    "Hedge End STW - River Downstream",
    "Hedge End STW - River Upstream",
    "Hedge End STW - Treatment Effluent",
    "Helens STW - River Downstream",
    "Helens STW - River Upstream",
    "Helens STW - Treatment Effluent",
    "Hemsworth STW - River Downstream",
    "Hemsworth STW - River Upstream",
    "Hemsworth STW - Treatment Effluent",
    "Henley on Thames STW - River Downstream",
    "Henley on Thames STW - River Upstream",
    "Henley on Thames STW - Treatment Effluent",
    "Heyford STW - River Downstream",
    "Heyford STW - Treatment Effluent",
    "High Halden STW - River Downstream",
    "High Halden STW - Treatment Effluent",
    "Highbridge STW - River Downstream",
    "Highbridge STW - River Upstream",
    "Highbridge STW - Treatment Effluent",
    "Hilmarton STW - River Downstream",
    "Hilmarton STW - Treatment Effluent",
    "Hinkley Point C STW - Treatment Effluent",
    "Hinkley Point C STW - Treatment Influent",
    "Hinxton STW - River Downstream",
    "Hinxton STW - Treatment Effluent",
    "Histon STW - River Downstream",
    "Histon STW - River Upstream",
    "Histon STW - Treatment Effluent",
    "Hoddesdon STW - River Downstream",
    "Hoddesdon STW - River Upstream",
    "Hoddesdon STW - Treatment Effluent",
    "Holbeach STW - River Downstream",
    "Holbeach STW - River Upstream",
    "Holbeach STW - Treatment Effluent",
    "Horden STW - River Downstream",
    "Horden STW - River Upstream",
    "Horden STW - Treatment Effluent",
    "Horley STW - River Downstream",
    "Horley STW - River Upstream",
    "Horley STW - Treatment Effluent",
    "Horncastle STW - River Downstream",
    "Horncastle STW - River Upstream",
    "Horncastle STW - Treatment Effluent",
    "Horningsea STW - River Downstream",
    "Horningsea STW - Treatment Effluent",
    "Horton Kirby STW - River Downstream",
    "Horton Kirby STW - River Upstream",
    "Horton Kirby STW - Treatment Effluent",
    "Houghton Regis STW - River Downstream",
    "Houghton Regis STW - River Upstream",
    "Houghton Regis STW - Treatment Effluent",
    "Huddersfield STW - River Downstream",
    "Huddersfield STW - River Upstream",
    "Huddersfield STW - Treatment Effluent",
    "Humber STW - Treatment Effluent",
    "Hungerford STW - River Downstream",
    "Hungerford STW - River Upstream",
    "Hungerford STW - Treatment Effluent",
    "Huntingdon STW - River Downstream",
    "Huntingdon STW - River Upstream",
    "Huntingdon STW - Treatment Effluent",
    "Ickleford STW - River Downstream",
    "Ickleford STW - River Upstream",
    "Ickleford STW - Treatment Effluent",
    "Icklingham STW - River Downstream",
    "Icklingham STW - Treatment Effluent",
    "Ilkeston STW - River Downstream",
    "Ilkeston STW - River Upstream",
    "Ilkeston STW - Treatment Effluent",
    "Immingham STW - Treatment Effluent",
    "Impington STW - River Downstream",
    "Impington STW - River Upstream",
    "Impington STW - Treatment Effluent",
    "Irvine STW - Treatment Effluent",
    "Keele University - Treatment Effluent",
    "Kendal STW - River Downstream",
    "Kendal STW - River Upstream",
    "Kendal STW - Treatment Effluent",
    "Kenilworth STW - River Downstream",
    "Kenilworth STW - River Upstream",
    "Kenilworth STW - Treatment Effluent",
    "Kensworth STW - River Downstream",
    "Kensworth STW - River Upstream",
    "Kensworth STW - Treatment Effluent",
    "Keresley STW - River Downstream",
    "Keresley STW - River Upstream",
    "Keresley STW - Treatment Effluent",
    "Kettering STW - River Downstream",
    "Kettering STW - River Upstream",
    "Kettering STW - Treatment Effluent",
    "Keyworth STW - River Downstream",
    "Keyworth STW - River Upstream",
    "Keyworth STW - Treatment Effluent",
    "Kidderminster STW - River Downstream",
    "Kidderminster STW - River Upstream",
    "Kidderminster STW - Treatment Effluent",
    "Kimpton STW - River Downstream",
    "Kimpton STW - River Upstream",
    "Kimpton STW - Treatment Effluent",
    "Kington STW - River Downstream",
    "Kington STW - River Upstream",
    "Kington STW - Treatment Effluent",
    "Kirby Lonsdale STW - River Downstream",
    "Kirby Lonsdale STW - River Upstream",
    "Kirby Lonsdale STW - Treatment Effluent",
    "Knaresborough STW - River Downstream",
    "Knaresborough STW - River Upstream",
    "Knaresborough STW - Treatment Effluent",
    "Knutsford STW - River Downstream",
    "Knutsford STW - River Upstream",
    "Knutsford STW - Treatment Effluent",
    "Lakenheath STW - River Downstream",
    "Lakenheath STW - River Upstream",
    "Lakenheath STW - Treatment Effluent",
    "Lambley STW - River Downstream",
    "Lambley STW - River Upstream",
    "Lambley STW - Treatment Effluent",
    "Lancaster STW - River Downstream",
    "Lancaster STW - River Upstream",
    "Lancaster STW - Treatment Effluent",
    "Langley Mill STW - River Downstream",
    "Langley Mill STW - River Upstream",
    "Langley Mill STW - Treatment Effluent",
    "Langwith STW - River Downstream",
    "Langwith STW - River Upstream",
    "Langwith STW - Treatment Effluent",
    "Laughton STW - River Downstream",
    "Laughton STW - River Upstream",
    "Laughton STW - Treatment Effluent",
    "Ledbury STW - River Downstream",
    "Ledbury STW - River Upstream",
    "Ledbury STW - Treatment Effluent",
    "Leeds STW - River Downstream",
    "Leeds STW - River Upstream",
    "Leeds STW - Treatment Effluent",
    "Leek STW - River Downstream",
    "Leek STW - River Upstream",
    "Leek STW - Treatment Effluent",
    "Leigh STW - River Downstream",
    "Leigh STW - River Upstream",
    "Leigh STW - Treatment Effluent",
    "Leighton Buzzard STW - River Downstream",
    "Leighton Buzzard STW - River Upstream",
    "Leighton Buzzard STW - Treatment Effluent",
    "Lewes STW - River Downstream",
    "Lewes STW - River Upstream",
    "Lewes STW - Treatment Effluent",
    "Lichfield STW - River Downstream",
    "Lichfield STW - River Upstream",
    "Lichfield STW - Treatment Effluent",
    "Lilleshall STW - River Downstream",
    "Lilleshall STW - Treatment Effluent",
    "Linchmere STW - River Downstream",
    "Linchmere STW - River Upstream",
    "Linchmere STW - Treatment Effluent",
    "Linton STW - River Downstream",
    "Linton STW - River Upstream",
    "Linton STW - Treatment Effluent",
    "Little Bedwyn STW - River Downstream",
    "Little Bedwyn STW - River Upstream",
    "Little Bedwyn STW - Treatment Effluent",
    "Little Melton STW - River Downstream",
    "Little Melton STW - Treatment Effluent",
    "Little Paxton STW - River Downstream",
    "Little Paxton STW - River Upstream",
    "Little Paxton STW - Treatment Effluent",
    "Little Wymondley STW - River Downstream",
    "Little Wymondley STW - River Upstream",
    "Little Wymondley STW - Treatment Effluent",
    "Llanfrechfa WWTW - Treatment Effluent",
    "Llanfrechfa WWTW - Treatment Influent",
    "Llantwit Major WWTW - River Downstream",
    "Llantwit Major WWTW - Treatment Effluent",
    "London Colney STW - River Downstream",
    "London Colney STW - River Upstream",
    "London Colney STW - Treatment Effluent",
    "Long Lawford STW - River Downstream",
    "Long Lawford STW - River Upstream",
    "Long Lawford STW - Treatment Effluent",
    "Long Marston STW - River Downstream",
    "Long Marston STW - River Upstream",
    "Long Marston STW - Treatment Effluent",
    "Long Melford STW - River Downstream",
    "Long Melford STW - Treatment Effluent",
    "Lonsdale STW - River Downstream",
    "Lonsdale STW - River Upstream",
    "Lonsdale STW - Treatment Effluent",
    "Louth STW - River Downstream",
    "Louth STW - River Upstream",
    "Louth STW - Treatment Effluent",
    "Lowestoft STW - Treatment Effluent",
    "Lower Gornal STW - River Downstream",
    "Lower Gornal STW - River Upstream",
    "Lower Gornal STW - Treatment Effluent",
    "Lower Tame STW - River Downstream",
    "Lower Tame STW - River Upstream",
    "Lower Tame STW - Treatment Effluent",
    "Lower Whitlingham STW - River Downstream",
    "Lower Whitlingham STW - River Upstream",
    "Lower Whitlingham STW - Treatment Effluent",
    "Ludlow STW - River Downstream",
    "Ludlow STW - River Upstream",
    "Ludlow STW - Treatment Effluent",
    "Luton STW - River Downstream",
    "Luton STW - River Upstream",
    "Luton STW - Treatment Effluent",
    "Lydiate Ash STW - River Downstream",
    "Lydiate Ash STW - River Upstream",
    "Lydiate Ash STW - Treatment Effluent",
    "Lyneham STW - River Downstream",
    "Lyneham STW - River Upstream",
    "Lyneham STW - Treatment Effluent",
    "Maidenhead STW - River Downstream",
    "Maidenhead STW - River Upstream",
    "Maidenhead STW - Treatment Effluent",
    "Malvern STW - River Downstream",
    "Malvern STW - River Upstream",
    "Malvern STW - Treatment Effluent",
    "Manchester Urmston STW - River Downstream",
    "Manchester Urmston STW - River Upstream",
    "Manchester Urmston STW - Treatment Effluent",
    "Manton STW - River Downstream",
    "Manton STW - River Upstream",
    "Manton STW - Treatment Effluent",
    "Marlborough STW - River Downstream",
    "Marlborough STW - River Upstream",
    "Marlborough STW - Treatment Effluent",
    "Marshgate STW - River Downstream",
    "Marshgate STW - River Upstream",
    "Marshgate STW - Treatment Effluent",
    "Marston STW - River Downstream",
    "Marston STW - River Upstream",
    "Marston STW - Treatment Effluent",
    "Matlock STW - River Downstream",
    "Matlock STW - River Upstream",
    "Matlock STW - Treatment Effluent",
    "Measham STW - River Downstream",
    "Measham STW - River Upstream",
    "Measham STW - Treatment Effluent",
    "Melbourne STW - River Downstream",
    "Melbourne STW - River Upstream",
    "Melbourne STW - Treatment Effluent",
    "Mellor Brook STW - River Downstream",
    "Mellor Brook STW - River Upstream",
    "Mellor Brook STW - Treatment Effluent",
    "Melton Mowbray STW - River Downstream",
    "Melton Mowbray STW - River Upstream",
    "Melton Mowbray STW - Treatment Effluent",
    "Meynell STW - River Downstream",
    "Meynell STW - Treatment Effluent",
    "Middleton STW - River Downstream",
    "Middleton STW - River Upstream",
    "Middleton STW - Treatment Effluent",
    "Middleton-on-the-Wolds STW - River Downstream",
    "Middleton-on-the-Wolds STW - Treatment Effluent",
    "Milford STW - River Downstream",
    "Milford STW - River Upstream",
    "Milford STW - Treatment Effluent",
    "Milford-on-Sea STW - River Downstream",
    "Milford-on-Sea STW - River Upstream",
    "Milford-on-Sea STW - Treatment Effluent",
    "Millom STW - River Downstream",
    "Millom STW - River Upstream",
    "Millom STW - Treatment Effluent",
    "Minworth STW - Treatment Effluent",
    "Mirfield STW - River Downstream",
    "Mirfield STW - River Upstream",
    "Mirfield STW - Treatment Effluent",
    "Monkswood STW - River Downstream",
    "Monkswood STW - River Upstream",
    "Monkswood STW - Treatment Effluent",
    "Moreton STW - River Downstream",
    "Moreton STW - River Upstream",
    "Moreton STW - Treatment Effluent",
    "Mow Cop STW - River Downstream",
    "Mow Cop STW - River Upstream",
    "Mow Cop STW - Treatment Effluent",
    "Mytholmroyd STW - River Downstream",
    "Mytholmroyd STW - River Upstream",
    "Mytholmroyd STW - Treatment Effluent",
    "Nailsea STW - River Downstream",
    "Nailsea STW - River Upstream",
    "Nailsea STW - Treatment Effluent",
    "Newark STW - River Downstream",
    "Newark STW - River Upstream",
    "Newark STW - Treatment Effluent",
    "Newbold on Avon STW - River Downstream",
    "Newbold on Avon STW - Treatment Effluent",
    "Newburn STW - River Downstream",
    "Newburn STW - Treatment Effluent",
    "Newdigate STW - River Downstream",
    "Newdigate STW - River Upstream",
    "Newdigate STW - Treatment Effluent",
    "Newent STW - River Downstream",
    "Newent STW - River Upstream",
    "Newent STW - Treatment Effluent",
    "Newport STW - River Downstream",
    "Newport STW - River Upstream",
    "Newport STW - Treatment Effluent",
    "Newquay STW - River Downstream",
    "Newquay STW - River Upstream",
    "Newquay STW - Treatment Effluent",
    "Newton Aycliffe STW - River Downstream",
    "Newton Aycliffe STW - River Upstream",
    "Newton Aycliffe STW - Treatment Effluent",
    "Newton Kyme STW - River Downstream",
    "Newton Kyme STW - Treatment Effluent",
    "North Creake STW - River Downstream",
    "North Creake STW - Treatment Effluent",
    "North Hykeham STW - River Downstream",
    "North Hykeham STW - River Upstream",
    "North Hykeham STW - Treatment Effluent",
    "North Thoresby STW - River Downstream",
    "North Thoresby STW - River Upstream",
    "North Thoresby STW - Treatment Effluent",
    "Northwich STW - River Downstream",
    "Northwich STW - River Upstream",
    "Northwich STW - Treatment Effluent",
    "Norton STW - River Downstream",
    "Norton STW - Treatment Effluent",
    "Nottingham STW - River Downstream",
    "Nottingham STW - River Upstream",
    "Nottingham STW - Treatment Effluent",
    "Nuneaton STW - River Downstream",
    "Nuneaton STW - River Upstream",
    "Nuneaton STW - Treatment Effluent",
    "Oakham STW - River Downstream",
    "Oakham STW - River Upstream",
    "Oakham STW - Treatment Effluent",
    "Oakhanger STW - River Downstream",
    "Oakhanger STW - Treatment Effluent",
    "Odiham STW - River Downstream",
    "Odiham STW - River Upstream",
    "Odiham STW - Treatment Effluent",
    "Old Basing STW - River Downstream",
    "Old Basing STW - River Upstream",
    "Old Basing STW - Treatment Effluent",
    "Oldbury on Severn STW - Treatment Effluent",
    "Oldbury on Severn STW - Treatment Influent",
    "Oldham STW - River Downstream",
    "Oldham STW - River Upstream",
    "Oldham STW - Treatment Effluent",
    "Olney STW - River Downstream",
    "Olney STW - River Upstream",
    "Olney STW - Treatment Effluent",
    "Ombersley STW - River Downstream",
    "Ombersley STW - River Upstream",
    "Ombersley STW - Treatment Effluent",
    "Orwell STW - River Downstream",
    "Orwell STW - Treatment Effluent",
    "Oswestry STW - River Downstream",
    "Oswestry STW - River Upstream",
    "Oswestry STW - Treatment Effluent",
    "Otford STW - River Downstream",
    "Otford STW - River Upstream",
    "Otford STW - Treatment Effluent",
    "Oxford STW - River Downstream",
    "Oxford STW - River Upstream",
    "Oxford STW - Treatment Effluent",
    "Padworth STW - River Downstream",
    "Padworth STW - River Upstream",
    "Padworth STW - Treatment Effluent",
    "Pakenham STW - River Downstream",
    "Pakenham STW - River Upstream",
    "Pakenham STW - Treatment Effluent",
    "Pangbourne STW - River Downstream",
    "Pangbourne STW - River Upstream",
    "Pangbourne STW - Treatment Effluent",
    "Parkgate STW - River Downstream",
    "Parkgate STW - Treatment Effluent",
    "Parr STW - River Downstream",
    "Parr STW - River Upstream",
    "Parr STW - Treatment Effluent",
    "Partney STW - River Downstream",
    "Partney STW - River Upstream",
    "Partney STW - Treatment Effluent",
    "Peaslake STW - River Downstream",
    "Peaslake STW - River Upstream",
    "Peaslake STW - Treatment Effluent",
    "Pelsall STW - River Downstream",
    "Pelsall STW - River Upstream",
    "Pelsall STW - Treatment Effluent",
    "Pembury STW - River Downstream",
    "Pembury STW - River Upstream",
    "Pembury STW - Treatment Effluent",
    "Pendleton STW - River Downstream",
    "Pendleton STW - River Upstream",
    "Pendleton STW - Treatment Effluent",
    "Penwortham STW - River Downstream",
    "Penwortham STW - River Upstream",
    "Penwortham STW - Treatment Effluent",
    "Pickworth STW - River Downstream",
    "Pickworth STW - River Upstream",
    "Pickworth STW - Treatment Effluent",
    "Piddle Hinton STW - River Downstream",
    "Piddle Hinton STW - River Upstream",
    "Piddle Hinton STW - Treatment Effluent",
    "Piddlehinton STW - River Downstream",
    "Piddlehinton STW - River Upstream",
    "Piddlehinton STW - Treatment Effluent",
    "Pinhoe STW - River Downstream",
    "Pinhoe STW - River Upstream",
    "Pinhoe STW - Treatment Effluent",
    "Pluckley STW - River Downstream",
    "Pluckley STW - River Upstream",
    "Pluckley STW - Treatment Effluent",
    "Plympton STW - River Downstream",
    "Plympton STW - Treatment Effluent",
    "Plymstock STW - River Downstream",
    "Plymstock STW - Treatment Effluent",
    "Pollington STW - River Downstream",
    "Pollington STW - Treatment Effluent",
    "Ponders End STW - River Downstream",
    "Ponders End STW - River Upstream",
    "Ponders End STW - Treatment Effluent",
    "Pontefract STW - River Downstream",
    "Pontefract STW - River Upstream",
    "Pontefract STW - Treatment Effluent",
    "Porth STW - Treatment Effluent",
    "Portsmouth - Treatment Effluent",
    "Potter Heigham STW - River Downstream",
    "Potter Heigham STW - Treatment Effluent",
    "Prestatyn STW - Treatment Effluent",
    "Prestatyn STW - Treatment Influent",
    "Preston STW - River Downstream",
    "Preston STW - River Upstream",
    "Preston STW - Treatment Effluent",
    "Princetown STW - River Downstream",
    "Princetown STW - River Upstream",
    "Princetown STW - Treatment Effluent",
    "Pudsey STW - River Downstream",
    "Pudsey STW - River Upstream",
    "Pudsey STW - Treatment Effluent",
    "Putney Vale STW - Treatment Effluent",
    "Queenborough STW - River Downstream",
    "Queenborough STW - River Upstream",
    "Queenborough STW - Treatment Effluent",
    "Radstock STW - River Downstream",
    "Radstock STW - River Upstream",
    "Radstock STW - Treatment Effluent",
    "Raglan WWTW - River Downstream",
    "Raglan WWTW - River Upstream",
    "Raglan WWTW - Treatment Effluent",
    "Ramsbottom STW - River Downstream",
    "Ramsbottom STW - River Upstream",
    "Ramsbottom STW - Treatment Effluent",
    "Ranskill STW - River Downstream",
    "Ranskill STW - Treatment Effluent",
    "Rauceby STW - River Downstream",
    "Rauceby STW - River Upstream",
    "Rauceby STW - Treatment Effluent",
    "Reading STW - River Downstream",
    "Reading STW - River Upstream",
    "Reading STW - Treatment Effluent",
    "Redditch STW - River Downstream",
    "Redditch STW - River Upstream",
    "Redditch STW - Treatment Effluent",
    "Reed STW - River Downstream",
    "Reed STW - River Upstream",
    "Reed STW - Treatment Effluent",
    "Reigate STW - River Downstream",
    "Reigate STW - River Upstream",
    "Reigate STW - Treatment Effluent",
    "Rochdale STW - River Downstream",
    "Rochdale STW - River Upstream",
    "Rochdale STW - Treatment Effluent",
    "Rolleston STW - River Downstream",
    "Rolleston STW - Treatment Effluent",
    "Romsey STW - River Downstream",
    "Romsey STW - River Upstream",
    "Romsey STW - Treatment Effluent",
    "Roughton STW - River Downstream",
    "Roughton STW - River Upstream",
    "Roughton STW - Treatment Effluent",
    "Rotherham STW - River Downstream",
    "Rotherham STW - River Upstream",
    "Rotherham STW - Treatment Effluent",
    "Rothwell STW - River Downstream",
    "Rothwell STW - River Upstream",
    "Rothwell STW - Treatment Effluent",
    "Rugeley STW - River Downstream",
    "Rugeley STW - River Upstream",
    "Rugeley STW - Treatment Effluent",
    "Rugby STW - River Downstream",
    "Rugby STW - River Upstream",
    "Rugby STW - Treatment Effluent",
    "Rushden STW - River Downstream",
    "Rushden STW - River Upstream",
    "Rushden STW - Treatment Effluent",
    "Rye Harbour STW - Treatment Effluent",
    "Salisbury STW - River Downstream",
    "Salisbury STW - River Upstream",
    "Salisbury STW - Treatment Effluent",
    "Saltend STW - Treatment Effluent",
    "Saltend STW - Treatment Influent",
    "Sandbach STW - River Downstream",
    "Sandbach STW - River Upstream",
    "Sandbach STW - Treatment Effluent",
    "Sandon STW - River Downstream",
    "Sandon STW - River Upstream",
    "Sandon STW - Treatment Effluent",
    "Saundersfoot STW - Treatment Effluent",
    "Sawston STW - River Downstream",
    "Sawston STW - River Upstream",
    "Sawston STW - Treatment Effluent",
    "Sawston STW - Treatment Influent",
    "Scorton STW - River Downstream",
    "Scorton STW - Treatment Effluent",
    "Selby STW - River Downstream",
    "Selby STW - River Upstream",
    "Selby STW - Treatment Effluent",
    "Selsley STW - River Downstream",
    "Selsley STW - River Upstream",
    "Selsley STW - Treatment Effluent",
    "Sheffield Blackburn Meadows STW - River Downstream",
    "Sheffield Blackburn Meadows STW - River Upstream",
    "Sheffield Blackburn Meadows STW - Treatment Effluent",
    "Sheffield Blackburn Meadows STW - Treatment Influent",
    "Shelf STW - River Downstream",
    "Shelf STW - River Upstream",
    "Shelf STW - Treatment Effluent",
    "Shepshed STW - River Downstream",
    "Shepshed STW - River Upstream",
    "Shepshed STW - Treatment Effluent",
    "Shepton Mallet STW - River Downstream",
    "Shepton Mallet STW - River Upstream",
    "Shepton Mallet STW - Treatment Effluent",
    "Shirley STW - River Downstream",
    "Shirley STW - River Upstream",
    "Shirley STW - Treatment Effluent",
    "Shrewsbury STW - River Downstream",
    "Shrewsbury STW - River Upstream",
    "Shrewsbury STW - Treatment Effluent",
    "Sibford STW - River Downstream",
    "Sibford STW - River Upstream",
    "Sibford STW - Treatment Effluent",
    "Sileby STW - River Downstream",
    "Sileby STW - River Upstream",
    "Sileby STW - Treatment Effluent",
    "Sissinghurst STW - River Downstream",
    "Sissinghurst STW - River Upstream",
    "Sissinghurst STW - Treatment Effluent",
    "Sittingbourne STW - River Downstream",
    "Sittingbourne STW - River Upstream",
    "Sittingbourne STW - Treatment Effluent",
    "Skegness STW - River Downstream",
    "Skegness STW - River Upstream",
    "Skegness STW - Treatment Effluent",
    "Sleaford STW - River Downstream",
    "Sleaford STW - River Upstream",
    "Sleaford STW - Treatment Effluent",
    "Slough STW - River Downstream",
    "Slough STW - River Upstream",
    "Slough STW - Treatment Effluent",
    "Soham STW - River Downstream",
    "Soham STW - Treatment Effluent",
    "Somerton STW - River Downstream",
    "Somerton STW - River Upstream",
    "Somerton STW - Treatment Effluent",
    "South Cave STW - River Downstream",
    "South Cave STW - River Upstream",
    "South Cave STW - Treatment Effluent",
    "South Hykeham STW - River Downstream",
    "South Hykeham STW - River Upstream",
    "South Hykeham STW - Treatment Effluent",
    "South Shields STW - River Downstream",
    "South Shields STW - River Upstream",
    "South Shields STW - Treatment Effluent",
    "South Witham STW - River Downstream",
    "South Witham STW - River Upstream",
    "South Witham STW - Treatment Effluent",
    "Southampton West STW - River Downstream",
    "Southampton West STW - River Upstream",
    "Southampton West STW - Treatment Effluent",
    "Southend STW - Treatment Effluent",
    "Spalding STW - River Downstream",
    "Spalding STW - River Upstream",
    "Spalding STW - Treatment Effluent",
    "Stafford STW - River Downstream",
    "Stafford STW - River Upstream",
    "Stafford STW - Treatment Effluent",
    "Stamford STW - River Downstream",
    "Stamford STW - River Upstream",
    "Stamford STW - Treatment Effluent",
    "Stanbridgeford STW - River Downstream",
    "Stanbridgeford STW - River Upstream",
    "Stanbridgeford STW - Treatment Effluent",
    "Stanhope STW - River Downstream",
    "Stanhope STW - River Upstream",
    "Stanhope STW - Treatment Effluent",
    "Stanground STW - River Downstream",
    "Stanground STW - River Upstream",
    "Stanground STW - Treatment Effluent",
    "Stanway STW - River Downstream",
    "Stanway STW - River Upstream",
    "Stanway STW - Treatment Effluent",
    "Staplehurst STW - River Downstream",
    "Staplehurst STW - River Upstream",
    "Staplehurst STW - Treatment Effluent",
    "Staveley STW - River Downstream",
    "Staveley STW - River Upstream",
    "Staveley STW - Treatment Effluent",
    "Steeple Claydon STW - River Downstream",
    "Steeple Claydon STW - River Upstream",
    "Steeple Claydon STW - Treatment Effluent",
    "Stevenage STW - River Downstream",
    "Stevenage STW - River Upstream",
    "Stevenage STW - Treatment Effluent",
    "Stoke Hammond STW - River Downstream",
    "Stoke Hammond STW - River Upstream",
    "Stoke Hammond STW - Treatment Effluent",
    "Stoke Orchard STW - River Downstream",
    "Stoke Orchard STW - Treatment Effluent",
    "Stoke-on-Trent STW - River Downstream",
    "Stoke-on-Trent STW - River Upstream",
    "Stoke-on-Trent STW - Treatment Effluent",
    "Stone STW - River Downstream",
    "Stone STW - River Upstream",
    "Stone STW - Treatment Effluent",
    "Stowmarket STW - River Downstream",
    "Stowmarket STW - River Upstream",
    "Stowmarket STW - Treatment Effluent",
    "Stowting STW - River Downstream",
    "Stowting STW - River Upstream",
    "Stowting STW - Treatment Effluent",
    "Stratford upon Avon STW - River Downstream",
    "Stratford upon Avon STW - River Upstream",
    "Stratford upon Avon STW - Treatment Effluent",
    "Sturminster Newton STW - River Downstream",
    "Sturminster Newton STW - River Upstream",
    "Sturminster Newton STW - Treatment Effluent",
    "Sunderland STW - River Downstream",
    "Sunderland STW - River Upstream",
    "Sunderland STW - Treatment Effluent",
    "Sutton STW - River Downstream",
    "Sutton STW - River Upstream",
    "Sutton STW - Treatment Effluent",
    "Sutton in Ashfield STW - River Downstream",
    "Sutton in Ashfield STW - River Upstream",
    "Sutton in Ashfield STW - Treatment Effluent",
    "Swadlincote STW - River Downstream",
    "Swadlincote STW - River Upstream",
    "Swadlincote STW - Treatment Effluent",
    "Swaffham STW - River Downstream",
    "Swaffham STW - River Upstream",
    "Swaffham STW - Treatment Effluent",
    "Swanage STW - River Downstream",
    "Swanage STW - River Upstream",
    "Swanage STW - Treatment Effluent",
    "Swanwick STW - River Downstream",
    "Swanwick STW - Treatment Effluent",
    "Swindon STW - River Downstream",
    "Swindon STW - River Upstream",
    "Swindon STW - Treatment Effluent",
    "Tankersley STW - River Downstream",
    "Tankersley STW - River Upstream",
    "Tankersley STW - Treatment Effluent",
    "Tarporley STW - River Downstream",
    "Tarporley STW - River Upstream",
    "Tarporley STW - Treatment Effluent",
    "Taunton STW - River Downstream",
    "Taunton STW - River Upstream",
    "Taunton STW - Treatment Effluent",
    "Tavistock STW - River Downstream",
    "Tavistock STW - River Upstream",
    "Tavistock STW - Treatment Effluent",
    "Tewkesbury STW - River Downstream",
    "Tewkesbury STW - River Upstream",
    "Tewkesbury STW - Treatment Effluent",
    "Thatcham STW - River Downstream",
    "Thatcham STW - River Upstream",
    "Thatcham STW - Treatment Effluent",
    "Thetford STW - River Downstream",
    "Thetford STW - River Upstream",
    "Thetford STW - Treatment Effluent",
    "Thorne STW - River Downstream",
    "Thorne STW - River Upstream",
    "Thorne STW - Treatment Effluent",
    "Thorney STW - River Downstream",
    "Thorney STW - River Upstream",
    "Thorney STW - Treatment Effluent",
    "Tidebrook STW - River Downstream",
    "Tidebrook STW - River Upstream",
    "Tidebrook STW - Treatment Effluent",
    "Tittesworth STW - River Downstream",
    "Tittesworth STW - River Upstream",
    "Tittesworth STW - Treatment Effluent",
    "Tivetshall STW - River Downstream",
    "Tivetshall STW - Treatment Effluent",
    "Todwick STW - River Downstream",
    "Todwick STW - River Upstream",
    "Todwick STW - Treatment Effluent",
    "Tonbridge STW - River Downstream",
    "Tonbridge STW - River Upstream",
    "Tonbridge STW - Treatment Effluent",
    "Torksey STW - River Downstream",
    "Torksey STW - Treatment Effluent",
    "Torksey STW - Treatment Influent",
    "Trowbridge STW - River Downstream",
    "Trowbridge STW - River Upstream",
    "Trowbridge STW - Treatment Effluent",
    "Tutbury STW - River Downstream",
    "Tutbury STW - River Upstream",
    "Tutbury STW - Treatment Effluent",
    "Tuxford STW - River Downstream",
    "Tuxford STW - River Upstream",
    "Tuxford STW - Treatment Effluent",
    "Uckfield STW - River Downstream",
    "Uckfield STW - River Upstream",
    "Uckfield STW - Treatment Effluent",
    "Upton on Severn STW - River Downstream",
    "Upton on Severn STW - River Upstream",
    "Upton on Severn STW - Treatment Effluent",
    "Uttoxeter STW - River Downstream",
    "Uttoxeter STW - River Upstream",
    "Uttoxeter STW - Treatment Effluent",
    "Ventnor STW - River Downstream",
    "Ventnor STW - River Upstream",
    "Ventnor STW - Treatment Effluent",
    "Wakefield STW - River Downstream",
    "Wakefield STW - River Upstream",
    "Wakefield STW - Treatment Effluent",
    "Walford Heath STW - River Downstream",
    "Walford Heath STW - Treatment Effluent",
    "Waltham on the Wolds STW - River Downstream",
    "Waltham on the Wolds STW - River Upstream",
    "Waltham on the Wolds STW - Treatment Effluent",
    "Wandleford STW - River Downstream",
    "Wandleford STW - Treatment Effluent",
    "Wargrave STW - River Downstream",
    "Wargrave STW - River Upstream",
    "Wargrave STW - Treatment Effluent",
    "Warton STW - River Downstream",
    "Warton STW - River Upstream",
    "Warton STW - Treatment Effluent",
    "Washington STW - River Downstream",
    "Washington STW - River Upstream",
    "Washington STW - Treatment Effluent",
    "Water Orton STW - River Downstream",
    "Water Orton STW - River Upstream",
    "Water Orton STW - Treatment Effluent",
    "Watford STW - River Downstream",
    "Watford STW - River Upstream",
    "Watford STW - Treatment Effluent",
    "Wath STW - River Downstream",
    "Wath STW - River Upstream",
    "Wath STW - Treatment Effluent",
    "Wednesbury STW - River Downstream",
    "Wednesbury STW - River Upstream",
    "Wednesbury STW - Treatment Effluent",
    "Welshwood STW - River Downstream",
    "Welshwood STW - River Upstream",
    "Welshwood STW - Treatment Effluent",
    "Welton STW - River Downstream",
    "Welton STW - Treatment Effluent",
    "West Hallam STW - River Downstream",
    "West Hallam STW - River Upstream",
    "West Hallam STW - Treatment Effluent",
    "Weston on the Green STW - River Downstream",
    "Weston on the Green STW - River Upstream",
    "Weston on the Green STW - Treatment Effluent",
    "Weston Super Mare STW - Treatment Effluent",
    "Weston Super Mare STW - Treatment Influent",
    "Wetherby STW - River Downstream",
    "Wetherby STW - River Upstream",
    "Wetherby STW - Treatment Effluent",
    "Whaley Bridge STW - River Downstream",
    "Whaley Bridge STW - River Upstream",
    "Whaley Bridge STW - Treatment Effluent",
    "Whaplode Drove STW - River Downstream",
    "Whaplode Drove STW - River Upstream",
    "Whaplode Drove STW - Treatment Effluent",
    "Wheatley STW - River Downstream",
    "Wheatley STW - River Upstream",
    "Wheatley STW - Treatment Effluent",
    "Whetstone STW - River Downstream",
    "Whetstone STW - River Upstream",
    "Whetstone STW - Treatment Effluent",
    "Whitchurch STW - River Downstream",
    "Whitchurch STW - River Upstream",
    "Whitchurch STW - Treatment Effluent",
    "White Waltham STW - River Downstream",
    "White Waltham STW - Treatment Effluent",
    "Whitfield STW - River Downstream",
    "Whitfield STW - Treatment Effluent",
    "Whitwick STW - River Downstream",
    "Whitwick STW - River Upstream",
    "Whitwick STW - Treatment Effluent",
    "Wick STW - Treatment Effluent",
    "Wigmore STW - River Downstream",
    "Wigmore STW - Treatment Effluent",
    "Willenhall STW - River Downstream",
    "Willenhall STW - River Upstream",
    "Willenhall STW - Treatment Effluent",
    "Willingham STW - River Downstream",
    "Willingham STW - River Upstream",
    "Willingham STW - Treatment Effluent",
    "Wilsthorpe STW - River Downstream",
    "Wilsthorpe STW - River Upstream",
    "Wilsthorpe STW - Treatment Effluent",
    "Wilton STW - River Downstream",
    "Wilton STW - Treatment Effluent",
    "Wimblington STW - River Downstream",
    "Wimblington STW - River Upstream",
    "Wimblington STW - Treatment Effluent",
    "Wincanton STW - River Downstream",
    "Wincanton STW - River Upstream",
    "Wincanton STW - Treatment Effluent",
    "Winchester STW - River Downstream",
    "Winchester STW - River Upstream",
    "Winchester STW - Treatment Effluent",
    "Wincle STW - River Downstream",
    "Wincle STW - River Upstream",
    "Wincle STW - Treatment Effluent",
    "Windsor STW - River Downstream",
    "Windsor STW - River Upstream",
    "Windsor STW - Treatment Effluent",
    "Winsford STW - River Downstream",
    "Winsford STW - River Upstream",
    "Winsford STW - Treatment Effluent",
    "Winslow STW - River Downstream",
    "Winslow STW - River Upstream",
    "Winslow STW - Treatment Effluent",
    "Winterborne STW - River Downstream",
    "Winterborne STW - River Upstream",
    "Winterborne STW - Treatment Effluent",
    "Winterton STW - River Downstream",
    "Winterton STW - River Upstream",
    "Winterton STW - Treatment Effluent",
    "Wirksworth STW - River Downstream",
    "Wirksworth STW - River Upstream",
    "Wirksworth STW - Treatment Effluent",
    "Wisbech STW - River Downstream",
    "Wisbech STW - River Upstream",
    "Wisbech STW - Treatment Effluent",
    "Wistaston STW - River Downstream",
    "Wistaston STW - River Upstream",
    "Wistaston STW - Treatment Effluent",
    "Witham STW - River Downstream",
    "Witham STW - River Upstream",
    "Witham STW - Treatment Effluent",
    "Wokingham STW - River Downstream",
    "Wokingham STW - River Upstream",
    "Wokingham STW - Treatment Effluent",
    "Wollaston STW - River Downstream",
    "Wollaston STW - River Upstream",
    "Wollaston STW - Treatment Effluent",
    "Wolverhampton STW - River Downstream",
    "Wolverhampton STW - River Upstream",
    "Wolverhampton STW - Treatment Effluent",
    "Wombourne STW - River Downstream",
    "Wombourne STW - River Upstream",
    "Wombourne STW - Treatment Effluent",
    "Woodley STW - River Downstream",
    "Woodley STW - River Upstream",
    "Woodley STW - Treatment Effluent",
    "Wool STW - River Downstream",
    "Wool STW - River Upstream",
    "Wool STW - Treatment Effluent",
    "Woolmer Green STW - River Downstream",
    "Woolmer Green STW - River Upstream",
    "Woolmer Green STW - Treatment Effluent",
    "Wootton Bassett STW - River Downstream",
    "Wootton Bassett STW - River Upstream",
    "Wootton Bassett STW - Treatment Effluent",
    "Worcester STW - River Downstream",
    "Worcester STW - River Upstream",
    "Worcester STW - Treatment Effluent",
    "Worksop STW - River Downstream",
    "Worksop STW - River Upstream",
    "Worksop STW - Treatment Effluent",
    "Worthing STW - River Downstream",
    "Worthing STW - River Upstream",
    "Worthing STW - Treatment Effluent",
    "Wrexham STW - Treatment Effluent",
    "Wrexham STW - Treatment Influent",
    "Wyke Regis STW - River Downstream",
    "Wyke Regis STW - River Upstream",
    "Wyke Regis STW - Treatment Effluent",
    "Yaxley STW - River Downstream",
    "Yaxley STW - River Upstream",
    "Yaxley STW - Treatment Effluent",
    "Yaxley STW - Treatment Influent",
    "York STW - River Downstream",
    "York STW - River Upstream",
    "York STW - Treatment Effluent",
    "Yoxall STW - River Downstream",
    "Yoxall STW - River Upstream",
    "Yoxall STW - Treatment Effluent",
    "Yoxford STW - River Downstream",
    "Yoxford STW - River Upstream",
    "Yoxford STW - Treatment Effluent",
    "Ystradfellte STW - Treatment Effluent"
]
    

    # Try to filter based on 'name' now that it's normalized
    if 'name' in df.columns:
        filtered_df = df[df['name'].isin(target_sites)]
        print(f"✅ Filtered {len(filtered_df)} rows using 'name' column")
        return filtered_df

    # If we still somehow miss the column
    raise ValueError("❌ Could not find a valid column name for site filtering.")
